// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nufvo23EJ9AYcWXG5ppmCa
// Component: 6lihKYwqi4

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Offer2 from "../../Offer2"; // plasmic-import: 6O_sz714mBswDr/component
import CwAdvert2 from "../../CwAdvert2"; // plasmic-import: UsYWXw6QCqj7Ct3/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_copy_of_lhp_3_30_23.module.css"; // plasmic-import: nufvo23EJ9AYcWXG5ppmCa/projectcss
import sty from "./PlasmicDisposable9.module.css"; // plasmic-import: 6lihKYwqi4/css

export type PlasmicDisposable9__VariantMembers = {};
export type PlasmicDisposable9__VariantsArgs = {};
type VariantPropType = keyof PlasmicDisposable9__VariantsArgs;
export const PlasmicDisposable9__VariantProps = new Array<VariantPropType>();

export type PlasmicDisposable9__ArgsType = {};
type ArgPropType = keyof PlasmicDisposable9__ArgsType;
export const PlasmicDisposable9__ArgProps = new Array<ArgPropType>();

export type PlasmicDisposable9__OverridesType = {
  root?: p.Flex<"div">;
  offer2?: p.Flex<typeof Offer2>;
  cwAdvert2?: p.Flex<typeof CwAdvert2>;
};

export interface DefaultDisposable9Props {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDisposable9__RenderFunc(props: {
  variants: PlasmicDisposable9__VariantsArgs;
  args: PlasmicDisposable9__ArgsType;
  overrides: PlasmicDisposable9__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <Offer2
              data-plasmic-name={"offer2"}
              data-plasmic-override={overrides.offer2}
              className={classNames("__wab_instance", sty.offer2)}
            />
          ) : null}
          <CwAdvert2
            data-plasmic-name={"cwAdvert2"}
            data-plasmic-override={overrides.cwAdvert2}
            className={classNames("__wab_instance", sty.cwAdvert2)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "offer2", "cwAdvert2"],
  offer2: ["offer2"],
  cwAdvert2: ["cwAdvert2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  offer2: typeof Offer2;
  cwAdvert2: typeof CwAdvert2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDisposable9__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDisposable9__VariantsArgs;
    args?: PlasmicDisposable9__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDisposable9__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDisposable9__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDisposable9__ArgProps,
          internalVariantPropNames: PlasmicDisposable9__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDisposable9__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDisposable9";
  } else {
    func.displayName = `PlasmicDisposable9.${nodeName}`;
  }
  return func;
}

export const PlasmicDisposable9 = Object.assign(
  // Top-level PlasmicDisposable9 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    offer2: makeNodeComponent("offer2"),
    cwAdvert2: makeNodeComponent("cwAdvert2"),

    // Metadata about props expected for PlasmicDisposable9
    internalVariantProps: PlasmicDisposable9__VariantProps,
    internalArgProps: PlasmicDisposable9__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDisposable9;
/* prettier-ignore-end */
