// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nufvo23EJ9AYcWXG5ppmCa
// Component: gx5PD9FdbLZLB

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { DataFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: ae7V86eNoXA/codeComponent
import { PlasmicHead } from "@plasmicapp/react-web"; // plasmic-import: i-DTG5VUVHSt/codeComponent
import NavArticle1 from "../../NavArticle1"; // plasmic-import: Jm27I2OupsUC4Z/component
import BodyArticle1 from "../../BodyArticle1"; // plasmic-import: tATSIvg-wEr20C/component

import { useScreenVariants as useScreenVariantsrolQiFvOio8R1Y } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ROLQiFvOIO8r1y/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_copy_of_lhp_3_30_23.module.css"; // plasmic-import: nufvo23EJ9AYcWXG5ppmCa/projectcss
import sty from "./PlasmicArticleInfo.module.css"; // plasmic-import: gx5PD9FdbLZLB/css

export type PlasmicArticleInfo__VariantMembers = {};
export type PlasmicArticleInfo__VariantsArgs = {};
type VariantPropType = keyof PlasmicArticleInfo__VariantsArgs;
export const PlasmicArticleInfo__VariantProps = new Array<VariantPropType>();

export type PlasmicArticleInfo__ArgsType = {};
type ArgPropType = keyof PlasmicArticleInfo__ArgsType;
export const PlasmicArticleInfo__ArgProps = new Array<ArgPropType>();

export type PlasmicArticleInfo__OverridesType = {
  root?: p.Flex<"div">;
  httpRestApiFetcher?: p.Flex<typeof DataFetcher>;
  pageMetadataOverride?: p.Flex<typeof PlasmicHead>;
  bodyArticle1?: p.Flex<typeof BodyArticle1>;
  head?: p.Flex<typeof PlasmicHead>;
};

export interface DefaultArticleInfoProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicArticleInfo__RenderFunc(props: {
  variants: PlasmicArticleInfo__VariantsArgs;
  args: PlasmicArticleInfo__ArgsType;
  overrides: PlasmicArticleInfo__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsrolQiFvOio8R1Y()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
          id={(() => {
            try {
              return $ctx.params.slug;
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
        >
          {true ? (
            <DataFetcher
              data-plasmic-name={"httpRestApiFetcher"}
              data-plasmic-override={overrides.httpRestApiFetcher}
              className={classNames("__wab_instance", sty.httpRestApiFetcher)}
              dataName={"fetchDyanamicData" as const}
              errorDisplay={
                <ph.DataCtxReader>
                  {$ctx => "Error fetching data"}
                </ph.DataCtxReader>
              }
              headers={{
                "Content-Type": "application/json",
                Accept: "application/json",
                Authorization: "Bearer keyVDvhyVSx5Ntbl3"
              }}
              loadingDisplay={
                <ph.DataCtxReader>{$ctx => "Loading..."}</ph.DataCtxReader>
              }
              method={"GET" as const}
              noLayout={false}
              url={(() => {
                try {
                  return (
                    "https://api.airtable.com/v0/appmM1mMqcDvugXhY/PlasmicCMS?filterByFormula=slug=" +
                    "'" +
                    $ctx.params.slug +
                    "'"
                  );
                } catch (e) {
                  if (e instanceof TypeError) {
                    return "https://api.airtable.com/v0/appmM1mMqcDvugXhY/PlasmicCMS?filterByFormula=slug=";
                  }
                  throw e;
                }
              })()}
            >
              <ph.DataCtxReader>
                {$ctx => (
                  <React.Fragment>
                    <PlasmicHead
                      data-plasmic-name={"pageMetadataOverride"}
                      data-plasmic-override={overrides.pageMetadataOverride}
                      className={classNames(
                        "__wab_instance",
                        sty.pageMetadataOverride
                      )}
                      description={(() => {
                        try {
                          return $ctx.fetchDyanamicData.records[0].fields[
                            "Step 1 SEO Description"
                          ];
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      title={(() => {
                        try {
                          return $ctx.fetchDyanamicData.records[0].fields[
                            "Step 1 SEO Title"
                          ];
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                    />

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <NavArticle1
                        className={classNames(
                          "__wab_instance",
                          sty.navArticle1__wpMLi
                        )}
                      />
                    ) : null}
                    <BodyArticle1
                      data-plasmic-name={"bodyArticle1"}
                      data-plasmic-override={overrides.bodyArticle1}
                      className={classNames("__wab_instance", sty.bodyArticle1)}
                    />

                    <NavArticle1
                      className={classNames(
                        "__wab_instance",
                        sty.navArticle1__o2Gk4
                      )}
                    />

                    <PlasmicHead
                      data-plasmic-name={"head"}
                      data-plasmic-override={overrides.head}
                      className={classNames("__wab_instance", sty.head)}
                      description={(() => {
                        try {
                          return $ctx.fetchDyanamicData.fields.paragraph1;
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      image={(() => {
                        try {
                          return undefined;
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      title={(() => {
                        try {
                          return $ctx.fetchDyanamicData.fields.heroHeadline;
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                    />
                  </React.Fragment>
                )}
              </ph.DataCtxReader>
            </DataFetcher>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "httpRestApiFetcher",
    "pageMetadataOverride",
    "bodyArticle1",
    "head"
  ],
  httpRestApiFetcher: [
    "httpRestApiFetcher",
    "pageMetadataOverride",
    "bodyArticle1",
    "head"
  ],
  pageMetadataOverride: ["pageMetadataOverride"],
  bodyArticle1: ["bodyArticle1"],
  head: ["head"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  httpRestApiFetcher: typeof DataFetcher;
  pageMetadataOverride: typeof PlasmicHead;
  bodyArticle1: typeof BodyArticle1;
  head: typeof PlasmicHead;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicArticleInfo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicArticleInfo__VariantsArgs;
    args?: PlasmicArticleInfo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicArticleInfo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicArticleInfo__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicArticleInfo__ArgProps,
          internalVariantPropNames: PlasmicArticleInfo__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicArticleInfo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicArticleInfo";
  } else {
    func.displayName = `PlasmicArticleInfo.${nodeName}`;
  }
  return func;
}

export const PlasmicArticleInfo = Object.assign(
  // Top-level PlasmicArticleInfo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    httpRestApiFetcher: makeNodeComponent("httpRestApiFetcher"),
    pageMetadataOverride: makeNodeComponent("pageMetadataOverride"),
    bodyArticle1: makeNodeComponent("bodyArticle1"),
    head: makeNodeComponent("head"),

    // Metadata about props expected for PlasmicArticleInfo
    internalVariantProps: PlasmicArticleInfo__VariantProps,
    internalArgProps: PlasmicArticleInfo__ArgProps,

    // Key-value metadata
    metadata: { title: "Meet The Newest Flavor Diffuser" },

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicArticleInfo;
/* prettier-ignore-end */
