// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nufvo23EJ9AYcWXG5ppmCa
// Component: 9UgeZIsDyXY2hZ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Offer2 from "../../Offer2"; // plasmic-import: 6O_sz714mBswDr/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_copy_of_lhp_3_30_23.module.css"; // plasmic-import: nufvo23EJ9AYcWXG5ppmCa/projectcss
import sty from "./PlasmicDisposable7.module.css"; // plasmic-import: 9UgeZIsDyXY2hZ/css

export type PlasmicDisposable7__VariantMembers = {};
export type PlasmicDisposable7__VariantsArgs = {};
type VariantPropType = keyof PlasmicDisposable7__VariantsArgs;
export const PlasmicDisposable7__VariantProps = new Array<VariantPropType>();

export type PlasmicDisposable7__ArgsType = {};
type ArgPropType = keyof PlasmicDisposable7__ArgsType;
export const PlasmicDisposable7__ArgProps = new Array<ArgPropType>();

export type PlasmicDisposable7__OverridesType = {
  root?: p.Flex<"div">;
  offer2?: p.Flex<typeof Offer2>;
};

export interface DefaultDisposable7Props {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDisposable7__RenderFunc(props: {
  variants: PlasmicDisposable7__VariantsArgs;
  args: PlasmicDisposable7__ArgsType;
  overrides: PlasmicDisposable7__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Offer2
            data-plasmic-name={"offer2"}
            data-plasmic-override={overrides.offer2}
            className={classNames("__wab_instance", sty.offer2)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "offer2"],
  offer2: ["offer2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  offer2: typeof Offer2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDisposable7__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDisposable7__VariantsArgs;
    args?: PlasmicDisposable7__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDisposable7__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDisposable7__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDisposable7__ArgProps,
          internalVariantPropNames: PlasmicDisposable7__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDisposable7__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDisposable7";
  } else {
    func.displayName = `PlasmicDisposable7.${nodeName}`;
  }
  return func;
}

export const PlasmicDisposable7 = Object.assign(
  // Top-level PlasmicDisposable7 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    offer2: makeNodeComponent("offer2"),

    // Metadata about props expected for PlasmicDisposable7
    internalVariantProps: PlasmicDisposable7__VariantProps,
    internalArgProps: PlasmicDisposable7__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDisposable7;
/* prettier-ignore-end */
